package com.zhlands.honey.Module;

import org.apache.commons.lang3.builder.ToStringBuilder;

public class PmForecast implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_forecast.fd_id
     *
     * @mbggenerated
     */
    private Long fdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_forecast.fd_time
     *
     * @mbggenerated
     */
    private String fdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_forecast.fd_city_id
     *
     * @mbggenerated
     */
    private String fdCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_forecast.fd_city_name
     *
     * @mbggenerated
     */
    private String fdCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_forecast.fd_type
     *
     * @mbggenerated
     */
    private String fdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_forecast.fd_level
     *
     * @mbggenerated
     */
    private Byte fdLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_forecast.properity
     *
     * @mbggenerated
     */
    private String properity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_forecast.fd_id
     *
     * @return the value of pm_forecast.fd_id
     *
     * @mbggenerated
     */
    public Long getFdId() {
        return fdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_forecast.fd_id
     *
     * @param fdId the value for pm_forecast.fd_id
     *
     * @mbggenerated
     */
    public void setFdId(Long fdId) {
        this.fdId = fdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_forecast.fd_time
     *
     * @return the value of pm_forecast.fd_time
     *
     * @mbggenerated
     */
    public String getFdTime() {
        return fdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_forecast.fd_time
     *
     * @param fdTime the value for pm_forecast.fd_time
     *
     * @mbggenerated
     */
    public void setFdTime(String fdTime) {
        this.fdTime = fdTime == null ? null : fdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_forecast.fd_city_id
     *
     * @return the value of pm_forecast.fd_city_id
     *
     * @mbggenerated
     */
    public String getFdCityId() {
        return fdCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_forecast.fd_city_id
     *
     * @param fdCityId the value for pm_forecast.fd_city_id
     *
     * @mbggenerated
     */
    public void setFdCityId(String fdCityId) {
        this.fdCityId = fdCityId == null ? null : fdCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_forecast.fd_city_name
     *
     * @return the value of pm_forecast.fd_city_name
     *
     * @mbggenerated
     */
    public String getFdCityName() {
        return fdCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_forecast.fd_city_name
     *
     * @param fdCityName the value for pm_forecast.fd_city_name
     *
     * @mbggenerated
     */
    public void setFdCityName(String fdCityName) {
        this.fdCityName = fdCityName == null ? null : fdCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_forecast.fd_type
     *
     * @return the value of pm_forecast.fd_type
     *
     * @mbggenerated
     */
    public String getFdType() {
        return fdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_forecast.fd_type
     *
     * @param fdType the value for pm_forecast.fd_type
     *
     * @mbggenerated
     */
    public void setFdType(String fdType) {
        this.fdType = fdType == null ? null : fdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_forecast.fd_level
     *
     * @return the value of pm_forecast.fd_level
     *
     * @mbggenerated
     */
    public Byte getFdLevel() {
        return fdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_forecast.fd_level
     *
     * @param fdLevel the value for pm_forecast.fd_level
     *
     * @mbggenerated
     */
    public void setFdLevel(Byte fdLevel) {
        this.fdLevel = fdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_forecast.properity
     *
     * @return the value of pm_forecast.properity
     *
     * @mbggenerated
     */
    public String getProperity() {
        return properity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_forecast.properity
     *
     * @param properity the value for pm_forecast.properity
     *
     * @mbggenerated
     */
    public void setProperity(String properity) {
        this.properity = properity == null ? null : properity.trim();
    }
    
    @Override
    public String toString()
    {
        return ToStringBuilder.reflectionToString(this);
    }
}